// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmSRdDEv48q9TH4zt-C9iftHVy8GOSqaQ',
    appId: '1:158542575596:web:810ecac778c4568886b2c9',
    messagingSenderId: '158542575596',
    projectId: 'rdv-app-1beb4',
    authDomain: 'rdv-app-1beb4.firebaseapp.com',
    storageBucket: 'rdv-app-1beb4.firebasestorage.app',
    measurementId: 'G-75RS78JJSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPpMQOe_xWFzIUWMBjE7WqEcEBO5rmIQ8',
    appId: '1:158542575596:android:1daf80c84e79610286b2c9',
    messagingSenderId: '158542575596',
    projectId: 'rdv-app-1beb4',
    storageBucket: 'rdv-app-1beb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDngJdb5ZJ9Ii4iMP3MuK60vkx5ZiVsJTc',
    appId: '1:158542575596:ios:d2e0fb0c7dd757cc86b2c9',
    messagingSenderId: '158542575596',
    projectId: 'rdv-app-1beb4',
    storageBucket: 'rdv-app-1beb4.firebasestorage.app',
    iosBundleId: 'com.example.rdvApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDngJdb5ZJ9Ii4iMP3MuK60vkx5ZiVsJTc',
    appId: '1:158542575596:ios:d2e0fb0c7dd757cc86b2c9',
    messagingSenderId: '158542575596',
    projectId: 'rdv-app-1beb4',
    storageBucket: 'rdv-app-1beb4.firebasestorage.app',
    iosBundleId: 'com.example.rdvApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmSRdDEv48q9TH4zt-C9iftHVy8GOSqaQ',
    appId: '1:158542575596:web:41a6f8679b0d3d1186b2c9',
    messagingSenderId: '158542575596',
    projectId: 'rdv-app-1beb4',
    authDomain: 'rdv-app-1beb4.firebaseapp.com',
    storageBucket: 'rdv-app-1beb4.firebasestorage.app',
    measurementId: 'G-LH1DXDSY0J',
  );
}
